@extends('adminlte::page')
@notifyCss

@section('content')




<table cellspacing="0" style="border-collapse:collapse; width:1833px">
	<tbody>
		<tr>
			<td style="border-bottom:none; border-left:none; border-right:none; border-top:1px solid black; height:93px; text-align:center; vertical-align:bottom; white-space:nowrap; width:62px"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;</span></span></span></td>
			<td colspan="20" style="border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:middle; white-space:nowrap; width:1693px"><span style="font-size:27px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">BALANCE MAQUILA DE REFINACION BIO D</span></span></strong></span>
				<br><a href="{{ route('weighing.create') }}" class="btn btn-primary ">Crear Registro</a>
			</td>
			<td style="border-bottom:none; border-left:none; border-right:none; border-top:none; vertical-align:bottom; white-space:nowrap; width:71px">&nbsp;

			</td>

		</tr>
		<tr>
			<td colspan="6" style="background-color:#d9d9d9; border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:1px solid black; height:21px; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;</span></span></strong></span></td>
			<td colspan="5" style="background-color:#d9d9d9; border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Datos de recepcion&nbsp;</span></span></strong></span></td>
			<td colspan="6" style="background-color:#d9d9d9; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">calculo maquila refinacion&nbsp;</span></span></strong></span></td>
<!-- 			<td colspan="4" style="background-color:#d9d9d9; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">refinado entregado&nbsp;</span></span></strong></span></td> -->
			<td style="border-bottom:none; border-left:none; border-right:none; border-top:none; vertical-align:bottom; white-space:nowrap">&nbsp;</td>
		</tr>
		<tr>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:1px solid black; border-right:1px solid black; border-top:none; height:68px; text-align:center; vertical-align:middle; white-space:normal; width:62px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">numero remision&nbsp;&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Neto</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Procedencia</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Placa&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:56px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Acidez remitida&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:none; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:73px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Humedad + impurezas remitida</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:1px solid black; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:58px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Fecha&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:143px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Numero tiquete&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:79px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;Neto recibido KG&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:56px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Acidez recibida</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:85px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Humedad + impurezas recibido</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:102px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">% Merma refinacion&nbsp; (AGL)&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:74px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;Neto agl a producir KG&nbsp;&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:86px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;Neto agl a cesionar a Palmeras&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:70px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;Neto agl a entregar Biod&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:94px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;Neto merma&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:86px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;RBD a entregar KG&nbsp;</span></span></strong></span></td>
<!-- 			<td style="background-color:#d9d9d9; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:82px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Fecha&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:108px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Remision</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:70px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Acidez oleica entregada&nbsp;</span></span></strong></span></td>
			<td style="background-color:#d9d9d9; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:normal; width:90px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;Cantidad Kg&nbsp;</span></span></strong></span></td> -->
			<td style="background-color:#d9d9d9; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:middle; white-space:normal; width:71px"><span style="font-size:13px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">Diferencias origen</span></span></strong></span></td>
		</tr>
		<tr>
			<td style="background-color:white; border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:17px; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">3511</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp; 31.350</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">Alianza Oriental SA</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">XIC607</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">3,69</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:none; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">0,18</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:1px solid black; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">14-ene</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">EMP0000000613</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 31.300</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">4,14</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">0,13</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">4,968</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1.555</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 777</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 777</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 313</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 29.432</span></span></strong></span></td>
<!-- 			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">18/01/2022</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:left; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">RP-0000009796</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">0,068</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 34.630</span></span></span></td> -->
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">-50</span></span></span></td>
		</tr>
		<tr>
			<td style="background-color:white; border-bottom:1px solid black; border-left:1px solid black; border-right:1px solid black; border-top:none; height:17px; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">3513</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp; 31.480</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">Alianza Oriental SA</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">XIC607</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">3,79</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:none; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">0,13</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:1px solid black; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">18-ene</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">EMP0000000614</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 31.470</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">4,2</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">0,15</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">5,040</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1.586</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 793</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 793</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 315</span></span></span></td>
			<td style="background-color:white; border-bottom:1px solid black; border-left:none; border-right:1px solid black; border-top:none; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><strong><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 29.569</span></span></strong></span></td>
<!-- 			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">18/01/2022</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:left; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">RP-0000009797</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:middle; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">0,061</span></span></span></td>
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; text-align:center; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 32.950</span></span></span></td> -->
			<td style="background-color:white; border-bottom:none; border-left:none; border-right:1px solid black; border-top:1px solid black; vertical-align:bottom; white-space:nowrap"><span style="font-size:15px"><span style="color:black"><span style="font-family:Calibri,sans-serif">-10</span></span></span></td>
		</tr>
	</tbody>
</table>




<!-- <x:notify-messages /> -->

@endsection

@notifyJs
